# Generated by Django 5.2.9 on 2025-12-12 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Log de Auditoría', 'verbose_name_plural': 'Logs de Auditoría'},
        ),
        migrations.AlterModelOptions(
            name='broker',
            options={'verbose_name': 'Corredor', 'verbose_name_plural': 'Corredores'},
        ),
        migrations.AlterModelOptions(
            name='taxqualification',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Calificación Tributaria', 'verbose_name_plural': 'Calificaciones Tributarias'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuarios'},
        ),
        migrations.RemoveField(
            model_name='taxqualification',
            name='amounts',
        ),
        migrations.RemoveField(
            model_name='taxqualification',
            name='factors',
        ),
        migrations.AddField(
            model_name='taxqualification',
            name='currency',
            field=models.CharField(choices=[('CLP', 'CLP - Peso Chileno'), ('COP', 'COP - Peso Colombiano'), ('PEN', 'PEN - Sol Peruano'), ('USD', 'USD - Dólar Estadounidense')], default='CLP', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=50, verbose_name='Acción Realizada'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.TextField(verbose_name='Detalles Técnicos'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Marca de Tiempo'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operador'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código Bolsa'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre Corredor'),
        ),
        migrations.AlterField(
            model_name='taxqualification',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='api.broker', verbose_name='Corredor'),
        ),
        migrations.AlterField(
            model_name='taxqualification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='taxqualification',
            name='exercise_year',
            field=models.IntegerField(verbose_name='Año Ejercicio'),
        ),
        migrations.AlterField(
            model_name='taxqualification',
            name='instrument',
            field=models.CharField(max_length=120, verbose_name='Instrumento / Nemotécnico'),
        ),
        migrations.AlterField(
            model_name='taxqualification',
            name='payment_date',
            field=models.DateField(verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='taxqualification',
            name='source',
            field=models.CharField(default='MANUAL', max_length=50, verbose_name='Origen Dato'),
        ),
        migrations.AlterField(
            model_name='taxqualification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.broker', verbose_name='Corredor Asociado'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Sistema'),
        ),
    ]
