# Generated by Django 5.2.9 on 2025-12-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_auditlog_options_alter_broker_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxqualification',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Ingreso Manual (Operador)'), ('CSV', 'Carga Masiva (Archivo)'), ('API', 'Integración Bolsa (Automático)')], default='MANUAL', max_length=50, verbose_name='Origen Dato'),
        ),
    ]
